# Generated by Django 5.0.3 on 2024-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.URLField(),
        ),
    ]
